{{- range $projectName, $project := .Values.projects }}
{{- range $destinationName, $grant := $project.grants }}
{{- $destination := index $.Values.platform.destinations $destinationName }}
{{- $grantName := include "linkerd-policies.grantName" (dict "project" $projectName "destination" $destinationName) }}
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: {{ $grantName | quote }}
  namespace: {{ $destination.namespace | quote }}
  labels:
    {{- include "linkerd-policies.labels" $ | nindent 4 }}
    linkerd-policy.gitops/project: {{ $projectName | quote }}
  annotations:
    linkerd-policy.gitops/owner: {{ $projectName | quote }}
spec:
  targetRef:
    group: policy.linkerd.io
    kind: Server
    name: {{ $destinationName | quote }}
  requiredAuthenticationRefs:
    - group: policy.linkerd.io
      kind: MeshTLSAuthentication
      name: {{ $grantName | quote }}
{{- end }}
{{- end }}
